// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apjbvfzyydykjprupfez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwamJ2Znp5eWR5a2pwcnVwZmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0ODc0MTYsImV4cCI6MjA2OTA2MzQxNn0.m2UlfGQPyZB-nGOu5owUH-djon81up_F3Ih3RuAnel0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});